apache/flink-connector-pulsar

- flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/sink/PulsarSinkITCase.java
- flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/testutils/function/ControlSource.java
- flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/testutils/runtime/PulsarRuntimeOperator.java
backport based on PR apache/flink#21411
> [BP-v3.0][FLINK-29830][Connector/Pulsar] Create the topic with schema before consuming messages in PulsarSinkITCase.

- flink-sql-connector-pulsar/pom.xml
This is a PR after https://github.com/apache/flink-connector-pulsar/pull/25, but we split them for speeding up the reviews.
> [FLINK-30489][Connector/Pulsar] Shade all the dependencies in flink-sql-connector-pulsar.

- flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/sink/PulsarSink.java
- flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/sink/PulsarSinkBuilder.java
Sink's java doc were also not updated in time.
> [hotfix] Fix incorrect java doc in PulsarSink and PulsarSinkBuilder.

- docs/content.zh/docs/connectors/datastream/pulsar.md
- docs/content/docs/connectors/datastream/pulsar.md
- docs/layouts/shortcodes/generated/pulsar_client_configuration.html
- docs/layouts/shortcodes/generated/pulsar_consumer_configuration.html
- docs/layouts/shortcodes/generated/pulsar_producer_configuration.html
- docs/layouts/shortcodes/generated/pulsar_source_configuration.html
- flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/common/config/PulsarClientFactory.java
- flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/common/config/PulsarOptions.java
- flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/sink/PulsarSinkOptions.java
- flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/sink/committer/PulsarCommitter.java
- flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/sink/config/PulsarSinkConfigUtils.java
- flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/sink/writer/message/PulsarMessage.java
- flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/PulsarSourceOptions.java
- flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/config/PulsarSourceConfigUtils.java
- flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/enumerator/topic/TopicNameUtils.java
- flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/source/reader/deserializer/GenericRecordDeserializationSchemaTest.java
- flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/testutils/PulsarTestSuiteBase.java
- flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/testutils/runtime/PulsarRuntime.java
- flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/testutils/runtime/container/PulsarContainerRuntime.java
- flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/testutils/runtime/remote/PulsarRemoteRuntime.java
- flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/testutils/runtime/singleton/PulsarSingletonRuntime.java
- flink-sql-connector-pulsar/pom.xml
- flink-sql-connector-pulsar/src/main/resources/META-INF/NOTICE
- pom.xml
This is a PR for bumping the `pulsar-client-all` to latest 2.11.0.
> [FLINK-30606][Connector/Pulsar] Bump the pulsar-client-all to latest 2.11.0.

- docs/layouts/shortcodes/generated/pulsar_producer_configuration.html
- flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/sink/PulsarSinkOptions.java
*Fix the wrong links in producer option docs*
- *Fix the wrong links in producer option docs.*
Please make sure both new and modified tests in this PR follows the conventions defined in our code quality
guide: https://flink.apache.org/contributing/code-style-and-quality-common.html#testing
*(Please pick either of the following options)*
This change is a code cleanup without any test coverage.
convenience.)*
> [FLINK-31618][docs] Fix the wrong links in producer option docs

- docs/layouts/shortcodes/generated/pulsar_admin_configuration.html
- docs/layouts/shortcodes/generated/pulsar_client_configuration.html
- docs/layouts/shortcodes/generated/pulsar_consumer_configuration.html
- docs/layouts/shortcodes/generated/pulsar_producer_configuration.html
- docs/layouts/shortcodes/generated/pulsar_sink_configuration.html
- docs/layouts/shortcodes/generated/pulsar_source_configuration.html
*Add the pulsar connector docs*
- *Add the pulsar connector docs.*
This change is a pr about docs without any test coverage.
convenience.)*
> [FLINK-31720][docs][Connector/Pulsar] Add the pulsar connector docs

- pom.xml
* Sync and correct dependencies of version that are out of sync or incorrect
* Set correct dependency versions and groupIds
convenience.)*
> [FLINK-31725] Synchronize dependency versions between Flink and flink-connector-pulsar

- .github/workflows/ci.yml
Avoid main branch CI jobs being canceled.
> [hotfix] Improve CI trigger and cancel strategy

- .github/workflows/daily.yml
- flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/reader/PulsarSourceFetcherManager.java
> [FLINK-31748] Dummy implementation to fix compilation failure

- .github/workflows/daily.yml
- flink-connector-pulsar/archunit-violations/f4d91193-72ba-4ce4-ad83-98f780dce581
> [hotfix] Workaround new violations message

- docs/data/pulsar.yml
- flink-connector-pulsar-e2e-tests/pom.xml
- flink-connector-pulsar/pom.xml
- flink-sql-connector-pulsar/pom.xml
- pom.xml
[build] Bump version to 4.2-SNAPSHOT
Please make sure both new and modified tests in this PR follows the conventions defined in our code quality
guide: https://flink.apache.org/contributing/code-style-and-quality-common.html#testing
*(Please pick either of the following options)*
convenience.)*
> [hotfix][build] Bump version to 4.2-SNAPSHOT

- docs/data/pulsar.yml
- flink-connector-pulsar-e2e-tests/pom.xml
- flink-connector-pulsar/pom.xml
- flink-sql-connector-pulsar/pom.xml
- pom.xml
hotfix: fix version in release branch
Please make sure both new and modified tests in this PR follows the conventions defined in our code quality
guide: https://flink.apache.org/contributing/code-style-and-quality-common.html#testing
*(Please pick either of the following options)*
This change is already covered by existing tests, such as *(please describe tests)*.
*(yes)*
convenience.)*
> [hotfix][build] Release branch should use SNAPSHOT version

- docs/content.zh/docs/connectors/datastream/pulsar.md
- docs/content/docs/connectors/datastream/pulsar.md
> [FLINK-33964] Drop admin docs reference

- docs/content.zh/docs/connectors/datastream/pulsar.md
- docs/content/docs/connectors/datastream/pulsar.md
> [BP][FLINK-33964][pulsar][docs] Drop admin docs reference

- docs/content.zh/docs/connectors/datastream/pulsar.md
- docs/content/docs/connectors/datastream/pulsar.md
> [FLINK-33964][pulsar][docs] Remove dead link

- .dlc.json
- .github/workflows/ci.yml
Add dead link check for connector document.
> [FLINK-33970] Add necessary checks for connector document

- docs/content.zh/docs/connectors/datastream/pulsar.md
- docs/content/docs/connectors/datastream/pulsar.md
> [BP][FLINK-33964][pulsar][docs] Remove dead link

- NOTICE
> [hotfix] Set copyright year to 2024

- flink-sql-connector-pulsar/src/main/resources/META-INF/NOTICE
Update copyright year to 2024.
Update copyright year to 2024 in NOTICE.
This change is a doc work without any test coverage.
> [hotfix] Update copyright year to 2024

- flink-sql-connector-pulsar/src/main/resources/META-INF/NOTICE
- pom.xml
Update the Pulsar dependency version to pick up patch fixes.
- Update `pulsar.version` to `3.0.2` in pom.xml.
This change added tests and can be verified as follows:
- Manually verified by running the Pulsar connector on a local Flink cluster.
Running this on a production workload did not uncover any issues.
convenience.)*
> [FLINK-33884] Update Pulsar dependency to 3.0.2 in Pulsar Connector
