apache/flink-connector-pulsar

flink-connector-pulsar/archunit-violations/stored.rules, flink-connector-pulsar/src/test/resources/archunit.properties, pom.xml
In ArchUnit 1.0.0 there was added a breaking change [1]
```
As mentioned in Enhancements/Core ArchRules will now by default reject evaluating if the set passed to the should-clause is empty. This will break existing rules that don't check any elements in their should-clause. You can restore the old behavior by setting the ArchUnit property archRule.failOnEmptyShould=false
```
As a result all the rules which do no match anything will fail.
Also since Flink 1.17-SNAPSHOT depends on 1.0.0 ArchUnit, this version was updated to be synced
[1] https://github.com/TNG/ArchUnit/releases/tag/v0.23.0
=> [FLINK-30426] Set `archRule.failOnEmptyShould = false` to return old behavior

pom.xml
Dependency tree from Flink's repo (before externalization):
```
[INFO] +- org.apache.pulsar:pulsar-client-all:jar:2.10.2:compile
[INFO] |  +- org.apache.pulsar:pulsar-client-api:jar:2.10.2:compile
[INFO] |  +- org.apache.pulsar:bouncy-castle-bc:jar:pkg:2.10.2:compile
[INFO] |  +- org.bouncycastle:bcpkix-jdk15on:jar:1.69:compile
[INFO] |  +- org.bouncycastle:bcprov-jdk15on:jar:1.69:compile
[INFO] |  +- org.bouncycastle:bcutil-jdk15on:jar:1.69:compile
[INFO] |  +- org.bouncycastle:bcprov-ext-jdk15on:jar:1.69:compile
```
Dependency tree from this repo (before this PR):
```
[INFO] |  \- org.apache.pulsar:pulsar-client-all:jar:2.10.2:compile
[INFO] |     +- org.apache.pulsar:pulsar-client-api:jar:2.10.2:compile
[INFO] |     +- org.apache.pulsar:bouncy-castle-bc:jar:pkg:2.10.2:compile
[INFO] | …
```
=> [FLINK-30427][Connector/Pulsar] Correct scope for bouncycastle dependencies

docs/layouts/shortcodes/generated/pulsar_source_configuration.html, flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/PulsarSourceOptions.java, flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/config/SourceConfiguration.java, flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/reader/PulsarPartitionSplitReader.java, flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/source/enumerator/cursor/StopCursorTest.java, flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/source/reader/PulsarPartitionSplitReaderTest.java, flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/source/reader/PulsarSourceReaderTest.java
When using Pulsar Source to consume data, if the data rate is small, e.g. 2 msg/s, there will be long periods of time when no messages are consumed.
This is caused by the default `PulsarSourceOptions.PULSAR_MAX_FETCH_TIME` and `PulsarSourceOptions.PULSAR_MAX_FETCH_RECORDS` options. Pulsar Source will try to pull messages until any conditions exceed. Such as fetch until 100 messages or fetch 10 seconds.
We have to add a new fetch time option for Pulsar Source. We would consider there is no message on the current topic if this fetch time exceeds. This would make sure the source would stop fetching messages when the 100ms exceed. Avoid hanging on small message income rates.
- Add new `PulsarSourceOptions.PULSAR_SINGLE_FETCH_TIME` option.
- Change the polling timeout to …
=> [FLINK-28870][Connector/Pulsar] Improve the Pulsar source performance when meeting small data rates.

docs/content.zh/docs/connectors/datastream/pulsar.md, docs/content/docs/connectors/datastream/pulsar.md
This pull request add an explain on correctly enable the checkpoint when use the exacly-once guarantee in Pulsar sink.
Change the document.
- Dependencies (does it add or upgrade a dependency): (no)
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
- The serializers: (no)
- The runtime per-record code paths (performance sensitive): (no)
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (no)
- The S3 file system connector: (yes / no / don't know)
- Does this pull request introduce a new feature? (no)
- If yes, how is the feature documented? (not applicable)
=> [FLINK-30681][Connector/Pulsar] Add a warning hint on the delivery guarantee document.

docs/content.zh/docs/connectors/datastream/pulsar.md, docs/content/docs/connectors/datastream/pulsar.md, docs/layouts/shortcodes/generated/pulsar_source_configuration.html, flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/PulsarSourceOptions.java, flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/config/SourceConfiguration.java, flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/enumerator/PulsarSourceEnumerator.java
This PR supports to set the `StartCursor` as the default start position for consuming.
- Add a new `PULSAR_RESET_SUBSCRIPTION_CURSOR` option in `PulsarSourceOptions`
This change is a minor change and don't have any tests.
- Dependencies (does it add or upgrade a dependency): (no)
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (no)
- The serializers: (no)
- The runtime per-record code paths (performance sensitive): (no)
- Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: (no)
- The S3 file system connector: (no)
- Does this pull request introduce a new feature? (yes)
- If yes, how is the feature documented? (docs, JavaDocs)
=> [FLINK-30654][Connector/Pulsar] Add an option to force consumption from StartCursor every time the application starts.

.github/PULL_REQUEST_TEMPLATE.md
*Add pull request template for `flink-connector-pulsar`.*
- *Introduce `PULL_REQUEST_TEMPLATE.md`.*
=> [FLINK-31067][Build] Add pull request template for flink-connector-pulsar

docs/layouts/shortcodes/generated/pulsar_admin_configuration.html, flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/common/config/PulsarAdminProxyBuilder.java, flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/common/config/PulsarClientFactory.java, flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/common/config/PulsarOptions.java, flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/common/handler/PulsarAdminInvocationHandler.java, flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/sink/writer/router/KeyHashTopicRouter.java, flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/sink/writer/router/RoundRobinTopicRouter.java, flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/PulsarSourceBuilder.java, flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/enumerator/PulsarSourceEnumerator.java, flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/enumerator/subscriber/PulsarSubscriber.java, flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/enumerator/subscriber/impl/BasePulsarSubscriber.java, flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/enumerator/subscriber/impl/TopicListSubscriber.java, flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/enumerator/subscriber/impl/TopicPatternSubscriber.java, flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/enumerator/topic/TopicNameUtils.java, flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/enumerator/topic/TopicPartition.java, flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/reader/PulsarPartitionSplitReader.java, flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/common/handler/PulsarAdminInvocationHandlerTest.java, flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/source/enumerator/subscriber/PulsarSubscriberTest.java, flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/source/reader/PulsarPartitionSplitReaderTest.java
This pull request reduce the topic metadata request by using a new protocol.
And introduce a common admin request proxy which can limit the request rates and retry the failed admin API request.
- Expose the num of thread count to user.
- Add new `PulsarOptions.PULSAR_ADMIN_REQUEST_RETRIES`, `PulsarOptions.PULSAR_ADMIN_REQUEST_WAIT_MILLIS`, `PulsarOptions.PULSAR_ADMIN_REQUEST_RATES` options to end users.
- Proxy the admin API into `PulsarAdminInvocationHandler`.
- Change the implementation in `TopicPatternSubscriber`. Add a new binary protocol for improve the performance.
- Cache all the non-partitons topics in `BasePulsarSubscriber`.
- Fix the bug in `TopicNameUtils`, we forget to make the partitions distinct.
- Correct the partition id setting in `TopicPartition`. Since it has been …
=> [FLINK-28959][Stream] Add retry and rate limit for admin request. Use binary protocol for topic filtering.

docs/content.zh/docs/connectors/datastream/pulsar.md, docs/content/docs/connectors/datastream/pulsar.md, flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/enumerator/subscriber/impl/TopicPatternSubscriber.java, flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/source/enumerator/subscriber/PulsarSubscriberTest.java, flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/testutils/runtime/PulsarRuntimeOperator.java, flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/testutils/runtime/container/PulsarContainerRuntime.java, flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/testutils/runtime/remote/PulsarRemoteRuntime.java
The connector can subscribe the topics by using regular expression. But it can't use any simple regex like `some.*`. Any regex should in `tenant/namespace/regex` format. Since Pulsar support simple topic name which live under `public` tenant and `default` namespace. I think it's awesome to support same ability in regex subscription.
- Change the internal design of `TopicPatternSubscriber`. The regex will be convert into a full regex by using `TopicName`.
There is [a known bug](https://github.com/apache/pulsar/issues/19316) in Pulsar 2.11.0. We can't subscribe the non-persistent topics by using regex now. We also create [a JIRA ticket](https://issues.apache.org/jira/browse/FLINK-31107) for tracking this bug.
This change added tests and can be verified as follows:
- …
=> [FLINK-31100][Stream] Support the short topic pattern subscriber on default tenant and namespace.

.github/workflows/daily.yml
*Adjust running time of nightly CI from weekly to daily.*
- *change cron expression of nighty ci yaml.*
=> [hotfix][Build] Adjust running time of nightly CI from weekly to daily.

flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/common/config/PulsarConfigValidator.java, flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/common/handler/PulsarAdminInvocationHandler.java, flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/common/schema/factories/PrimitiveSchemaFactory.java, flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/sink/writer/PulsarWriter.java, flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/sink/writer/router/KeyHashTopicRouter.java, flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/sink/writer/topic/MetadataListener.java, flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/sink/writer/topic/ProducerRegister.java, flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/config/PulsarConsumerBuilder.java, flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/enumerator/topic/TopicNameUtils.java, flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/enumerator/topic/TopicPartition.java, flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/reader/PulsarPartitionSplitReader.java, flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/sink/writer/router/RoundRobinTopicRouterTest.java, flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/source/enumerator/PulsarSourceEnumStateSerializerTest.java, flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/source/enumerator/PulsarSourceEnumeratorTest.java, flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/source/reader/PulsarPartitionSplitReaderTest.java, flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/source/reader/PulsarSourceReaderTest.java, flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/testutils/function/ControlSource.java, flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/testutils/runtime/PulsarRuntimeOperator.java, flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/testutils/runtime/singleton/PulsarSingletonRuntime.java, flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/testutils/sink/PulsarSinkTestContext.java
* Replace dependency on Flink-Shaded for connectors, since externalized connectors shouldn't rely on Flink-Shaded
- Removed all occurrences of `org.apache.flink.shaded.guava30.com` with `org.apache.pulsar.shade.com`
convenience.)*
=> [FLINK-31676][Connector/Pulsar] Replace Shaded Guava from Flink with Shaded Guava from Pulsar

docs/content.zh/docs/connectors/datastream/pulsar.md, docs/content/docs/connectors/datastream/pulsar.md
*Fix connector artifact shortcode for v3.0 branch document.*
- Using `connector_artifact` instead of `artifact`.
=> [hotfix] Fix connector artifact shortcode for document.

docs/content.zh/docs/connectors/datastream/pulsar.md, docs/content/docs/connectors/datastream/pulsar.md, docs/data/pulsar.yml
*Python connector download link should refer to the url defined in externalized repository.*
convenience.)*
=> [hotfix] Python connector download link should refer to the url defined in externalized repository

docs/content.zh/docs/connectors/datastream/pulsar.md, docs/content/docs/connectors/datastream/pulsar.md, docs/data/pulsar.yml
=> [BP-3.0][hotfix] Python connector download link should refer to the url defined in externalized repository

flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/common/schema/PulsarSchema.java, flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/common/schema/PulsarSchemaUtils.java, flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/testutils/runtime/container/PulsarContainerRuntime.java, flink-sql-connector-pulsar/src/main/resources/META-INF/NOTICE, pom.xml
Upgrade pulsar-client version to work with OAuth2
Existing tests should pass.
convenience.)*
=> [FLINK-32003] Upgrade pulsar-client version to work with OAuth2

docs/content.zh/docs/connectors/datastream/pulsar.md, docs/content/docs/connectors/datastream/pulsar.md, docs/data/pulsar.yml
Backport to `v4.0` as flink track this branch to render documentation.
=> [BP-4.0][FLINK-32024][docs] Short code related to externalized connector retrieve version from its own data yaml

flink-connector-pulsar-e2e-tests/pom.xml, flink-connector-pulsar/pom.xml, flink-sql-connector-pulsar/pom.xml, pom.xml
Stop bundling flink-connector-base.
Ref - FLINK-30400
This change is a code cleanup without any test coverage.
=> [FLINK-30400][build] Stop bundling flink-connector-base

.github/workflows/ci.yml, .github/workflows/daily.yml
1.18.x supports jdk 17, so it would make sense to add tests against java 17
gha
This change is a trivial rework 
=> [FLINK-33815][Connector / Pulsar] Add tests against jdk17 for pulsar connector

flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/enumerator/assigner/SplitAssignerImpl.java, flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/source/enumerator/assigner/SplitAssignerImplTest.java
This PR fixes a bug in partition owner logic returning `-1` for the partition owner, and is an alternative fix to the one proposed in https://github.com/apache/flink-connector-pulsar/pull/84. 
The subtask ID to which we try to assign a split should always be within `[0, parallelism-1]`. The bug occurs because a non-partitioned topic has `partitionId = -1` and the hash logic for certain topic names will yield `startIndex = 0`. Since the `%` operator can return negative values, the owner ID returned is `-1`. Replacing `%` with `floorMod` fixes this issue.
- Use `floorMod` instead of `%` so that `calculatePartitionOwner` cannot return a negative value.
This change added tests and can be verified as follows:
- Unit test to check that a split is assigned for different non-partitioned topic …
=> [FLINK-34629] Fix invalid subtask assignment for non-partitioned topics

.github/workflows/ci.yml, .github/workflows/daily.yml
The PR will allow to differentiate between Pulsar connector statistics and others with name ci
GHA name change
This change is a trivial rework
=> [FLINK-34961] Use dedicated CI name for Pulsar connector to differentiate it in infra-reports

pom.xml
This closes https://github.com/apache/flink-connector-pulsar/pull/83.
=> [FLINK-35182] Bump org.apache.commons:commons-compress from 1.24.0 to 1.26.1 for Flink Pulsar connector

flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/sink/config/SinkConfiguration.java, flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/source/config/SourceConfiguration.java
getLong and getInteger are removing in Flink 2.0, we should refactor them to get method.
Note: It blocks https://github.com/apache/flink/pull/25000.
Because flink-python module depends on the `flink-sql-connector-pulsar` , version : `4.0.0-1.17`.
But when `getLong and getInteger` are removed, `flink-sql-connector-pulsar` and `4.0.0-1.17` is still using them. So the CI will be failed.
https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=62127&view=logs&j=9cada3cb-c1d3-5621-16da-0f718fb86602&t=c67e71ed-6451-5d26-8920-5a8cf9651901&l=25266
=> [hotfix] Refactor callers that use deprecated get/setXXX of Configuration
